<template>
  <b-div
    padding="3"
    margin="b-2"
    background-color="primary"
    text-color="white"
  >
    .bg-primary
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="secondary"
    text-color="white"
  >
    .bg-secondary
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="success"
    text-color="white"
  >
    .bg-success
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="danger"
    text-color="white"
  >
    .bg-danger
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="warning"
    text-color="dark"
  >
    .bg-warning
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="info"
    text-color="dark"
  >
    .bg-info
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="light"
    text-color="dark"
  >
    .bg-light
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="dark"
    text-color="white"
  >
    .bg-dark
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="body"
    text-color="dark"
  >
    .bg-body
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="white"
    text-color="dark"
  >
    .bg-white
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="transparent"
    text-color="dark"
  >
    .bg-transparent
  </b-div>
</template>
