<template>
  <b-div
    padding="3"
    margin="b-2"
    background-color="primary"
    text-color="white"
    background-gradient
  >
    .bg-primary.bg-gradient
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="secondary"
    text-color="white"
    background-gradient
  >
    .bg-secondary.bg-gradient
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="success"
    text-color="white"
    background-gradient
  >
    .bg-success.bg-gradient
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="danger"
    text-color="white"
    background-gradient
  >
    .bg-danger.bg-gradient
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="warning"
    text-color="dark"
    background-gradient
  >
    .bg-warning.bg-gradient
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="info"
    text-color="dark"
    background-gradient
    class="p-3 mb-2 bg-info bg-gradient text-dark"
  >
    .bg-info.bg-gradient
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="light"
    text-color="dark"
    background-gradient
  >
    .bg-light.bg-gradient
  </b-div>
  <b-div
    padding="3"
    margin="b-2"
    background-color="dark"
    text-color="white"
    background-gradient
  >
    .bg-dark.bg-gradient
  </b-div>
</template>
