<template>
  <b-table responsive>
    <thead>
      <tr>
        <th>Breakpoint</th>
        <th>Class infix</th>
        <th>Dimensions</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>X-Small</td>
        <td>
          <em>None</em>
        </td>
        <td>&lt;576px</td>
      </tr>
      <tr>
        <td>Small</td>
        <td>
          <code>sm</code>
        </td>
        <td>&ge;576px</td>
      </tr>
      <tr>
        <td>Medium</td>
        <td>
          <code>md</code>
        </td>
        <td>&ge;768px</td>
      </tr>
      <tr>
        <td>Large</td>
        <td>
          <code>lg</code>
        </td>
        <td>&ge;992px</td>
      </tr>
      <tr>
        <td>Extra large</td>
        <td>
          <code>xl</code>
        </td>
        <td>&ge;1200px</td>
      </tr>
      <tr>
        <td>Extra extra large</td>
        <td>
          <code>xxl</code>
        </td>
        <td>&ge;1400px</td>
      </tr>
    </tbody>
  </b-table>
</template>
