<template>
  <ul>
    <li><code>align-items="start"</code></li>
    <li><code>align-items="end"</code></li>
    <li><code>align-items="center"</code></li>
    <li><code>align-items="baseline"</code></li>
    <li><code>align-items="stretch"</code></li>
    <li><code>align-items="sm-start"</code></li>
    <li><code>align-items="sm-end"</code></li>
    <li><code>align-items="sm-center"</code></li>
    <li><code>align-items="sm-baseline"</code></li>
    <li><code>align-items="sm-stretch"</code></li>
    <li><code>align-items="md-start"</code></li>
    <li><code>align-items="md-end"</code></li>
    <li><code>align-items="md-center"</code></li>
    <li><code>align-items="md-baseline"</code></li>
    <li><code>align-items="md-stretch"</code></li>
    <li><code>align-items="lg-start"</code></li>
    <li><code>align-items="lg-end"</code></li>
    <li><code>align-items="lg-center"</code></li>
    <li><code>align-items="lg-baseline"</code></li>
    <li><code>align-items="lg-stretch"</code></li>
    <li><code>align-items="xl-start"</code></li>
    <li><code>align-items="xl-end"</code></li>
    <li><code>align-items="xl-center"</code></li>
    <li><code>align-items="xl-baseline"</code></li>
    <li><code>align-items="xl-stretch"</code></li>
    <li><code>align-items="xxl-start"</code></li>
    <li><code>align-items="xxl-end"</code></li>
    <li><code>align-items="xxl-center"</code></li>
    <li><code>align-items="xxl-baseline"</code></li>
    <li><code>align-items="xxl-stretch"</code></li>
  </ul>
</template>
