<template>
  <ul>
    <li><code>flex-order="0"</code></li>
    <li><code>flex-order="1"</code></li>
    <li><code>flex-order="2"</code></li>
    <li><code>flex-order="3"</code></li>
    <li><code>flex-order="4"</code></li>
    <li><code>flex-order="5"</code></li>
    <li><code>flex-order="sm-0"</code></li>
    <li><code>flex-order="sm-1"</code></li>
    <li><code>flex-order="sm-2"</code></li>
    <li><code>flex-order="sm-3"</code></li>
    <li><code>flex-order="sm-4"</code></li>
    <li><code>flex-order="sm-5"</code></li>
    <li><code>flex-order="md-0"</code></li>
    <li><code>flex-order="md-1"</code></li>
    <li><code>flex-order="md-2"</code></li>
    <li><code>flex-order="md-3"</code></li>
    <li><code>flex-order="md-4"</code></li>
    <li><code>flex-order="md-5"</code></li>
    <li><code>flex-order="lg-0"</code></li>
    <li><code>flex-order="lg-1"</code></li>
    <li><code>flex-order="lg-2"</code></li>
    <li><code>flex-order="lg-3"</code></li>
    <li><code>flex-order="lg-4"</code></li>
    <li><code>flex-order="lg-5"</code></li>
    <li><code>flex-order="xl-0"</code></li>
    <li><code>flex-order="xl-1"</code></li>
    <li><code>flex-order="xl-2"</code></li>
    <li><code>flex-order="xl-3"</code></li>
    <li><code>flex-order="xl-4"</code></li>
    <li><code>flex-order="xl-5"</code></li>
    <li><code>flex-order="xxl-0"</code></li>
    <li><code>flex-order="xxl-1"</code></li>
    <li><code>flex-order="xxl-2"</code></li>
    <li><code>flex-order="xxl-3"</code></li>
    <li><code>flex-order="xxl-4"</code></li>
    <li><code>flex-order="xxl-5"</code></li>
  </ul>
</template>
