<template>
  <b-table responsive>
    <thead>
      <tr>
        <th>Size</th>
        <th>Class</th>
        <th>Modal max-width</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Small</td>
        <td>
          <code>.modal-sm</code>
        </td>
        <td>
          <code>300px</code>
        </td>
      </tr>
      <tr>
        <td>Default</td>
        <td class="text-muted">
          None
        </td>
        <td>
          <code>500px</code>
        </td>
      </tr>
      <tr>
        <td>Large</td>
        <td>
          <code>.modal-lg</code>
        </td>
        <td>
          <code>800px</code>
        </td>
      </tr>
      <tr>
        <td>Extra large</td>
        <td>
          <code>.modal-xl</code>
        </td>
        <td>
          <code>1140px</code>
        </td>
      </tr>
    </tbody>
  </b-table>
</template>
