<template>
  <b-table responsive>
    <thead>
      <tr>
        <th>Class</th>
        <th>Availability</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <code>.modal-fullscreen</code>
        </td>
        <td>Always</td>
      </tr>
      <tr>
        <td>
          <code>.modal-fullscreen-sm-down</code>
        </td>
        <td>
          Below
          <code>576px</code>
        </td>
      </tr>
      <tr>
        <td>
          <code>.modal-fullscreen-md-down</code>
        </td>
        <td>
          Below
          <code>768px</code>
        </td>
      </tr>
      <tr>
        <td>
          <code>.modal-fullscreen-lg-down</code>
        </td>
        <td>
          Below
          <code>992px</code>
        </td>
      </tr>
      <tr>
        <td>
          <code>.modal-fullscreen-xl-down</code>
        </td>
        <td>
          Below
          <code>1200px</code>
        </td>
      </tr>
      <tr>
        <td>
          <code>.modal-fullscreen-xxl-down</code>
        </td>
        <td>
          Below
          <code>1400px</code>
        </td>
      </tr>
    </tbody>
  </b-table>
</template>
