<template>
  <ListGroupList>
    <ListGroupItem
      flex
      justify-content="between"
      align-items="center"
    >
      A list item
      <Badge
        background-color="primary"
        pill
      >
        14
      </Badge>
    </ListGroupItem>
    <ListGroupItem
      flex
      justify-content="between"
      align-items="center"
    >
      A second list item
      <Badge
        background-color="primary"
        pill
      >
        2
      </Badge>
    </ListGroupItem>
    <ListGroupItem
      flex
      justify-content="between"
      align-items="center"
    >
      A third list item
      <Badge
        background-color="primary"
        pill
      >
        1
      </Badge>
    </ListGroupItem>
  </ListGroupList>
</template>
