<template>
  <b-div tab-content>
    <b-div
      id="home"
      tab-pane="fade"
      show
      active
      role="tabpanel"
    >
      ...
    </b-div>
    <b-div
      id="profile"
      tab-pane="fade"
      role="tabpanel"
    >
      ...
    </b-div>
    <b-div
      id="messages"
      tab-pane="fade"
      role="tabpanel"
    >
      ...
    </b-div>
    <b-div
      id="settings"
      tab-pane="fade"
      role="tabpanel"
    >
      ...
    </b-div>
  </b-div>
</template>
