<template>
  <b-div role="tabpanel">
    <!-- List group -->
    <ListGroupList
      id="myList"
      tab-pane
      role="tablist"
    >
      <ListGroupItemAction
        active
        toggle="list"
        href="#home"
        role="tab"
      >
        Home
      </ListGroupItemAction>
      <ListGroupItemAction
        toggle="list"
        href="#profile"
        role="tab"
      >
        Profile
      </ListGroupItemAction>
      <ListGroupItemAction
        toggle="list"
        href="#messages"
        role="tab"
      >
        Messages
      </ListGroupItemAction>
      <ListGroupItemAction
        toggle="list"
        href="#settings"
        role="tab"
      >
        Settings
      </ListGroupItemAction>
    </ListGroupList>

    <!-- Tab panes -->
    <b-div tab-content>
      <b-div
        id="home"
        active
        tab-pane
        role="tabpanel"
      >
        ...
      </b-div>
      <b-div
        id="profile"
        tab-pane
        role="tabpanel"
      >
        ...
      </b-div>
      <b-div
        id="messages"
        tab-pane
        role="tabpanel"
      >
        ...
      </b-div>
      <b-div
        id="settings"
        tab-pane
        role="tabpanel"
      >
        ...
      </b-div>
    </b-div>
  </b-div>
</template>
