<template>
  <Nav
    nav="pills"
    flex-direction="column sm-row"
  >
    <NavLink
      flex-fill="sm"
      text-alignment="sm-center"
      active
    >
      Active
    </NavLink>
    <NavLink
      flex-fill="sm"
      text-alignment="sm-center"
    >
      Much longer nav link
    </NavLink>
    <NavLink
      flex-fill="sm"
      text-alignment="sm-center"
    >
      Link
    </NavLink>
    <NavLink
      flex-fill="sm"
      text-alignment="sm-center"
      disabled
    >
      Disabled
    </NavLink>
  </Nav>
</template>
