<template>
  <b-span
    placeholder
    col="12"
  />
  <b-span
    placeholder
    col="12"
    background-color="primary"
  />
  <b-span
    placeholder
    col="12"
    background-color="secondary"
  />
  <b-span
    placeholder
    col="12"
    background-color="success"
  />
  <b-span
    placeholder
    col="12"
    background-color="danger"
  />
  <b-span
    placeholder
    col="12"
    background-color="warning"
  />
  <b-span
    placeholder
    col="12"
    background-color="info"
  />
  <b-span
    placeholder
    col="12"
    background-color="light"
  />
  <b-span
    placeholder
    col="12"
    background-color="dark"
  />
</template>
