<template>
  <b-div flex="sm">
    <b-div
      :opacity="100"
      padding="3"
      margin="2"
      background-color="primary"
      text-color="light"
      font-weight="bold"
      rounded
    >
      100%
    </b-div>
    <b-div
      :opacity="75"
      padding="3"
      margin="2"
      background-color="primary"
      text-color="light"
      font-weight="bold"
      rounded
    >
      75%
    </b-div>
    <b-div
      :opacity="50"
      padding="3"
      margin="2"
      background-color="primary"
      text-color="light"
      font-weight="bold"
      rounded
    >
      50%
    </b-div>
    <b-div
      :opacity="25"
      padding="3"
      margin="2"
      background-color="primary"
      text-color="light"
      font-weight="bold"
      rounded
    >
      25%
    </b-div>
  </b-div>
</template>
